services:
  - type: web
    name: flask-hello-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
